Desafio JR - PL/force-app/main/default/objects/DevUser__c/DevUser__c.object-meta.xml
<CustomObject>
    <label>DevUser</label>
    <nameField>
        <label>DevUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DevUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Desafio JR - PL/force-app/main/default/objects/DevUser__c/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Desafio JR - PL/force-app/main/default/objects/DevUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Desafio JR - PL/force-app/main/default/classes/Test/DevUserBatchTest/DevUserBatchTest.cls
@isTest
public class DevUserBatchTest {
    
    @isTest
    public static void completedRecords(){
        DevUser__c devUserTest = new DevUser__c(Name = 'Teste User', Login__c = 'octocat');
        insert devUserTest;
        
        String mockResponse = '{"login":"octocat","id":583231,"type":"User","bio":"GitHub mascot"}';
        
        Test.setMock(HttpCalloutMock.class, new GitHubMock(200, mockResponse));
        
        Test.startTest();
        Database.executeBatch(new DevUserBatch(new Set<Id>{devUserTest.Id}));
        Test.stopTest();
        
        DevUser__c updatedDevUser = [SELECT Id, Login__c, ExternalId__c, Type__c, Bio__c FROM DevUser__c WHERE Id = :devUserTest.Id];
        System.assertEquals('octocat', updatedDevUser.Login__c, 'Login should be octocat');
        System.assertEquals(583231, updatedDevUser.ExternalId__c, 'ExternalId should be 583231');
        System.assertEquals('User', updatedDevUser.Type__c, 'Type should be User');
        System.assertEquals('GitHub mascot', updatedDevUser.Bio__c, 'Bio should be GitHub mascot');
    }
}