DesafioPricing/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de ligação com o Estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing /force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <label>Freight</label>
    <nameField>
        <label>Freight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freight</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/Freight__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para cidade.</description>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Freight</relationshipLabel>
    <relationshipName>Freight</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Freight__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para país.</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Freight</relationshipLabel>
    <relationshipName>Freight</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Freight__c/fields/FreightValue__c.field-meta.xml
<CustomField>
    <fullName>FreightValue__c</fullName>
    <description>Valor do frete.</description>
    <label>FreightValue</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Freight__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Freight</relationshipLabel>
    <relationshipName>Freight</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para cidade.</description>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para país.</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/FreightValue__c.field-meta.xml
<CustomField>
    <fullName>FreightValue__c</fullName>
    <description>Valor do frete.</description>
    <label>FreightValue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ligação com o País em que o estado pertence</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/classes/Services/PricingService/FreightService/FreightService.cls
public class FreightService{
    
    private static void addKeys(List<String> keys, Id productId, List<Id> locationsIds) {
        for (Id iLocations : locationsIds) {
            if (productId != null && iLocations != null) {
                keys.add(productId + '_' + iLocations);
            }
        }
    }
    
    private static List<String> buildFreightKeys(OrderItem item, Order order, Id hierarchyId) {
        List<String> keys = new List<String>();
        
        List<Id> productsIds = new List<Id>{ item.Product2Id, hierarchyId };
        List<Id> locationsIds = new List<Id>{ order.City__c, order.State__c, order.Country__c };
        
        for (Id iProduct2 : productsIds) {
            addKeys(keys, iProduct2, locationsIds);
        }
        
        return keys;
    }
    
    public static Decimal findFreight(OrderItem item, Order order, Map<String, Freight__c> mapFreight, Id hierarchyId){
        List<String> keys = buildFreightKeys(item, order, hierarchyId);
        
        for (String iKey: keys) {
            if (mapFreight.containsKey(iKey)) {
                return mapFreight.get(iKey).FreightValue__c;
            }
        }
        return 0;
    }
}