DesafioPricing/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de ligação com o Estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>DistributionCenter</label>
    <nameField>
        <label>DistributionCenter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DistributionCenters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/DistributionCenter__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para cidade.</description>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>DistributionCenters</relationshipLabel>
    <relationshipName>DistributionCenters</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/DistributionCenter__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para país.</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>DistributionCenters</relationshipLabel>
    <relationshipName>DistributionCenters</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/DistributionCenter__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>DistributionCenters</relationshipLabel>
    <relationshipName>DistributionCenters</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para endereço.</description>
    <label>AccountAddress</label>
    <referenceTo>AccountAdd__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para cidade.</description>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para país.</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <description>Data de entrega do pedido.</description>
    <label>DeliveryDate</label>
    <type>Date</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Order/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para centro de distribuição.</description>
    <label>DistributionCenter</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/FreightType__c.field-meta.xml
<CustomField>
    <fullName>FreightType__c</fullName>
    <description>Tipo de frete.</description>
    <label>FreightType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Condição de pagamento.</description>
    <label>PaymentCondition</label>
    <referenceTo>PaymentCondition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/PaymentCondition__c/PaymentCondition__c.object-meta.xml
<CustomObject>
    <label>PaymentCondition</label>
    <nameField>
        <label>aymentCondition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PaymentConditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ligação com o País em que o estado pertence</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/classes/API/DTO/DataIntegrationFields.cls
global with sharing class DataIntegrationFields {
	public interface FieldData {
		List<String> getRequiredFields();
		String getFieldKey();
		String getFieldId();
		String getExternalId();
		SObject deserialize();
	}

	public interface FieldDataChild {
		List<String> getRequiredFields();
		String getFieldId();
		String getFieldExternal();
		String getParentId();
		String getParentKey();
		SObject deserialize();
	}

	//ou faço um select ou faço addres.City__c se ele mandar o obj inteiro
	global class OrderINData implements FieldData { // extends OrderBase
		public String externalId;
		public String status;
		public Date effectiveDate;
		public Date deliveryDate;
		public String shippingType;
		public String accountExternalId;
		public String pricebook2ExternalId;
		public String distributionCenter;
		public String cityExternalId;
		public String stateExternalId;
		public String countryExternalId;
		public String paymentTerms;

		public List<OrderItemINData> orderItemList {get; set;}

		public Order deserialize() {
			return new Order(
				ExternalId__c	= this.externalId,
				Status			= this.status,
				EffectiveDate	= this.effectiveDate,
				DeliveryDate__c	= this.deliveryDate,
				FreightType__c	= this.shippingType,
				Account			= new Account(ExternalId__c = this.accountExternalId),
				Pricebook2		= new Pricebook2(ExternalId__c = this.pricebook2ExternalId),
				DistributionCenter__r = new DistributionCenter__c(ExternalId__c = this.distributionCenter),
				City__r         = new City__c(ExternalId__c = this.cityExternalId),
				State__r        = new State__c(ExternalId__c = this.stateExternalId),
				Country__r      = new Country__c(ExternalId__c = this.countryExternalId),
				PaymentCondition__r = new PaymentCondition__c(ExternalId__c = this.paymentTerms)
			);
		}

		public List<String> getRequiredFields() {
			return new List<String>{
				'ExternalId__c',
				'EffectiveDate',
				'Status'
			};
		}
		public List<String> getRequiredLookups() {
			return new List<String>{
				'AccountId',
				'Pricebook2Id'
			};
		}

		public String getFieldKey() {
			return 'ExternalId__c';
		}
		public String getFieldId() {
			return 'Id';
		}
		public String getExternalId() {
			return this.externalId;
		}
	}
	global class OrderItemINData implements FieldDataChild { // extends OrderItemBase
		public String id;
		public String externalId;
		public Decimal quantity;
		public Decimal unitPrice;
		public String orderExternalId;
		public String productExternalId;
		public String pricebookEntryExternalId;

		public OrderItem deserialize() {
			OrderItem orderItem = new OrderItem(
				ExternalId__c	= this.externalId,
				Quantity		= this.quantity,
				UnitPrice		= this.unitPrice
			);

			if (this.id == null || this.id == '') {
				orderItem.Order				= new Order(ExternalId__c = this.orderExternalId);
				orderItem.Product2			= new Product2(ExternalId__c = this.productExternalId);
				orderItem.PricebookEntry	= new PricebookEntry(ExternalId__c = this.pricebookEntryExternalId);
			}
			else orderItem.Id = this.id;

			return orderItem;
		}

		public List<String> getRequiredFields() {
			return new List<String>{
				'UnitPrice',
				'Quantity',
				'ExternalId__c'
			};
		}
		public List<String> getRequiredLookups() {
			return new List<String>{
				'OrderId',
				'Product2Id',
				'PricebookEntryId'
			};
		}

		public String getFieldId() {
			return 'Id';
		}
		public String getFieldExternal() {
			return 'ExternalId__c';
		}
		public String getParentId() {
			return 'OrderId';
		}
		public String getParentKey() {
			return this.orderExternalId;
		}
	}

	global virtual class Response {
		public String salesforceId;
		public String externalId;
		public String sobjectType;
		public Boolean hasError;
		public String errorMessage;

		public void success(String salesforceId, String externalId, String sobjectType){
			this.salesforceId	= salesforceId;
			this.externalId		= externalId;
			this.sobjectType	= sobjectType;
			this.hasError		= false;
		}

		public void error(String externalId, String errorMessage, String sobjectType){
			this.externalId		= externalId;
			this.sobjectType	= sobjectType;
			this.hasError		= true;
			this.errorMessage	= errorMessage;
		}

		public void error(String salesforceId, String externalId, String errorMessage, String sobjectType){
			this.salesforceId	= salesforceId;
			this.externalId		= externalId;
			this.sobjectType	= sobjectType;
			this.hasError		= true;
			this.errorMessage	= errorMessage;
		}
	}
	global class ResponseParent extends Response {
		public List<DataIntegrationFields.Response> items;
	}

	public class CalloutResponse {
		public Boolean hasError;
		public String errorMessage;

		public ResponseParametersWrapper parsedResponse;
		public List<ResponseParametersWrapper> parsedResponses;

		public CalloutResponse(String errorMessage) {
			this.hasError = true;
			this.errorMessage = errorMessage;
		}
		public CalloutResponse(ResponseParametersWrapper response, Boolean hasError) {
			this.hasError = hasError;
			this.errorMessage = '';
			this.parsedResponse = response;
		}
		public CalloutResponse(List<ResponseParametersWrapper> responseList, Boolean hasError) {
			this.hasError = hasError;
			this.errorMessage = '';
			this.parsedResponses = responseList;
		}
	}

	public class ResponseParametersWrapper { // Adaptar Esta Class Para os Campos que Virá de Resposta da Integração OUT
		public Boolean hasError;
		public String errorMessage;
		public String salesforceId;
		public String externalId;
		public String sobjectType;

		public List<ResponseParametersWrapper> items;
	}

	public class RequestList { // Alterar o Nome das Variaveis Se Necessário
		List<OrderParameters> orderRequestList;

		public RequestList(List<DataIntegrationFields.OrderParameters> orderRequestList) {
			this.orderRequestList = orderRequestList;
		}
	}

	//configurar para p da livia
	public class OrderParameters {
		public String externalId;
		public String status;
		public Date effectiveDate;
		public Date deliveryDate;
		public String accountExternalId;
		public String pricebook2ExternalId;
		public String paymentTerms;
		public String distributionCenter;
		public String shippingType;
		public String address;
		public String billingAddressId;

		public OrderItemParameters[] orderItemList;

		public OrderParameters(Order order) {
			this.externalId = order.ExternalId__c;
			this.status = order.Status;
			this.effectiveDate = order.EffectiveDate;
			this.deliveryDate = order.DeliveryDate__c;
			this.accountExternalId = order.Account.ExternalId__c;
			this.pricebook2ExternalId = order.Pricebook2.ExternalId__c;
			this.paymentTerms = order.PaymentCondition__r.ExternalId__c;
			this.distributionCenter = order.DistributionCenter__r.ExternalId__c;
			this.shippingType = 'CIF';
			this.address = order.AccountAddress__r.ExternalId__c;
			this.billingAddressId = order.AccountAddress__r.ExternalId__c;

			this.orderItemList = new List<OrderItemParameters>();

			for (OrderItem orderItem : Order.OrderItems)
				orderItemList.add(new OrderItemParameters(orderItem));
		}
	}

	public class OrderItemParameters {
		public String externalId;
		public Decimal quantity;
		public Decimal unitPrice;
		public String orderExternalId;
		public String productExternalId;
		public String pricebookEntryExternalId;

		public OrderItemParameters(OrderItem orderItem) {
			this.externalId = orderItem.ExternalId__c;
			this.quantity = orderItem.Quantity;
			this.unitPrice = orderItem.UnitPrice;
			this.orderExternalId = orderItem.Order.ExternalId__c;
			this.productExternalId = orderItem.Product2.ExternalId__c;
			this.pricebookEntryExternalId = orderItem.PricebookEntry.ExternalId__c;
		}
	}

	public class ResponseAccessToken {
		public String access_token;
		public String error;
		public String error_description;
	}
}