DesafioPricing/force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relacionado ao Grupo de Clientes.</description>
    <label>AccountGroup</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <label>AccountGroup</label>
    <nameField>
        <label>AccountGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de ligação com o Estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing /force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <label>Freight</label>
    <nameField>
        <label>Freight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freight</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/Freight__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para cidade.</description>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Freight</relationshipLabel>
    <relationshipName>Freight</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Freight__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para país.</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Freight</relationshipLabel>
    <relationshipName>Freight</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Freight__c/fields/FreightValue__c.field-meta.xml
<CustomField>
    <fullName>FreightValue__c</fullName>
    <description>Valor do frete.</description>
    <label>FreightValue</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Freight__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Freight</relationshipLabel>
    <relationshipName>Freight</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <label>Margem</label>
    <nameField>
        <label>Margem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing /force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para grupo de conta.</description>
    <label>AccountGroup</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Margem__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para cidade.</description>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Margem__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para país.</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Margem__c/fields/MarginValuePercent__c.field-meta.xml
<CustomField>
    <fullName>MarginValuePercent__c</fullName>
    <description>Percentual da margem.</description>
    <label>MarginValuePercent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/Margem__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para cidade.</description>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para país.</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/Order/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup para estado.</description>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/DiscountPercentage__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercentage__c</fullName>
    <description>Percentual do desconto.</description>
    <label>DiscountPercentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Valor do desconto.</description>
    <label>DiscountValue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/FinalPrice__c.field-meta.xml
<CustomField>
    <fullName>FinalPrice__c</fullName>
    <description>Preço final.</description>
    <label>FinalPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/FreightValue__c.field-meta.xml
<CustomField>
    <fullName>FreightValue__c</fullName>
    <description>Valor do frete.</description>
    <label>FreightValue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/MarginPercentage__c.field-meta.xml
<CustomField>
    <fullName>MarginPercentage__c</fullName>
    <description>Percentual da margem.</description>
    <label>MarginPercentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/PriceWithoutMargin__c.field-meta.xml
<CustomField>
    <fullName>PriceWithoutMargin__c</fullName>
    <description>Preço sem margem.</description>
    <label>PriceWithoutMargin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/OrderItem/fields/ProductionCost__c.field-meta.xml
<CustomField>
    <fullName>ProductionCost__c</fullName>
    <description>Custo de produção.</description>
    <label>ProductionCost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/TaxPercentage__c.field-meta.xml
<CustomField>
    <fullName>TaxPercentage__c</fullName>
    <description>Percentual do imposto.</description>
    <label>TaxPercentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ligação com o País em que o estado pertence</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

DesafioPricing/force-app/main/default/classes/Services/PricingService/PricingService.cls
public class PricingService {
    
    //Frete - Especificações (Produto > Hierarquia | Cidade > Estado > Pais)
    public static Decimal findFreightValue(OrderItem item, Order pedido, Map<String, Freight__c> mapFrete, Id h) {
        Id p = item.Product2Id; //produto
        Id c = pedido.City__c; //cidade
        Id e = pedido.State__c; //estado
        Id pa = pedido.Country__c; //pais
        
        if (mapFrete.containsKey(p + '_' + c)) return mapFrete.get(p + '_' + c).FreightValue__c;
        if (mapFrete.containsKey(p + '_' + e)) return mapFrete.get(p + '_' + e).FreightValue__c;
        if (mapFrete.containsKey(p + '_' + pa)) return mapFrete.get(p + '_' + pa).FreightValue__c;
        if (mapFrete.containsKey(h + '_' + c)) return mapFrete.get(h + '_' + c).FreightValue__c;
        if (mapFrete.containsKey(h + '_' + e)) return mapFrete.get(h + '_' + e).FreightValue__c;
        if (mapFrete.containsKey(h + '_' + pa)) return mapFrete.get(h + '_' + pa).FreightValue__c;
        
        return 0;
    }
    
    //Margem - Especificações (Produto > Hierarquia | Cliente > Grupo de Contas | cidade> estado > País)
    public static Margem__c findMargin(OrderItem item, Order pedido, Map<String, Margem__c> mapMargin, Id h, Account cliente) {
        Id p = item.Product2Id; //produto
        Id a = pedido.AccountId; //account
        Id g = cliente.AccountGroup__c; //grupo e contas
        Id c = pedido.City__c; //cidade
        Id e = pedido.State__c; //estado
        Id pa = pedido.Country__c; //pais
        
        
        if (mapMargin.containsKey(p + '_' + a + '_' + c)) return mapMargin.get(p + '_' + a + '_' + c);
        if (mapMargin.containsKey(p + '_' + a + '_' + e)) return mapMargin.get(p + '_' + a + '_' + e);
        if (mapMargin.containsKey(p + '_' + a + '_' + pa)) return mapMargin.get(p + '_' + a + '_' + pa);
        if (mapMargin.containsKey(p + '_' + g + '_' + c)) return mapMargin.get(p + '_' + g + '_' + c);
        if (mapMargin.containsKey(p + '_' + g + '_' + e)) return mapMargin.get(p + '_' + g + '_' + e);
        if (mapMargin.containsKey(p + '_' + g + '_' + pa)) return mapMargin.get(p + '_' + g + '_' + pa);
        
        if (mapMargin.containsKey(h + '_' + a + '_' + c)) return mapMargin.get(h + '_' + a + '_' + c);
        if (mapMargin.containsKey(h + '_' + a + '_' + e)) return mapMargin.get(h + '_' + a + '_' + e);
        if (mapMargin.containsKey(h + '_' + a + '_' + pa)) return mapMargin.get(h + '_' + a + '_' + pa);
        if (mapMargin.containsKey(h + '_' + g + '_' + c)) return mapMargin.get(h + '_' + g + '_' + c);
        if (mapMargin.containsKey(h + '_' + g + '_' + e)) return mapMargin.get(h + '_' + g + '_' + e);
        if (mapMargin.containsKey(h + '_' + g + '_' + pa)) return mapMargin.get(h + '_' + g + '_' + pa);
        
        return new Margem__c(MarginValuePercent__c = 0);
    }
    
    public static void calculateFinalPrice(OrderItem item, Decimal frete, Margem__c margem, Decimal impostoPercent, Decimal custo) {
        Decimal mPerc = (margem != null && margem.MarginValuePercent__c != null) ? margem.MarginValuePercent__c : 0;
        Decimal iPerc = (impostoPercent != null) ? impostoPercent : 0;
        Decimal custoProd = (custo != null) ? custo : 0;
        Decimal freteVal = (frete != null) ? frete : 0;
        
        //preco base
        Decimal precoBase = custoProd + freteVal;
        
        //preco sem margem
        Decimal precoSemMargem = precoBase * (1 + (iPerc / 100));
        
        //preco final
        Decimal precoCalculado = precoSemMargem * (1 + (mPerc / 100));
        
        // preenchimento
        item.ProductionCost__c = custoProd;   
        item.MarginPercentage__c = mPerc;
        item.FreightValue__c = freteVal;
        item.TaxPercentage__c = iPerc;
        item.PriceWithoutMargin__c = precoSemMargem; // preco sem margem
        item.FinalPrice__c = precoCalculado; // preco final, item pedido 

        //garante q o unitPrice não seja null
        Decimal unitPriceDigitado = (item.UnitPrice != null) ? item.UnitPrice : 0;
        
        // D. Cálculo do Desconto (Percent)
        if (precoCalculado > 0) {
            item.DiscountPercentage__c = (precoCalculado - unitPriceDigitado) / precoCalculado;
            item.DiscountValue__c = precoCalculado - unitPriceDigitado;
        }
        
        item.UnitPrice = item.FinalPrice__c;
    }
}