DesafioPricing /force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <label>Margem</label>
    <nameField>
        <label>Margem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPricing/force-app/main/default/objects/Margem__c/fields/MarginValuePercent__c.field-meta.xml
<CustomField>
    <fullName>MarginValuePercent__c</fullName>
    <description>Percentual da margem.</description>
    <label>MarginValuePercent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/DiscountPercentage__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercentage__c</fullName>
    <description>Percentual do desconto.</description>
    <label>DiscountPercentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Valor do desconto.</description>
    <label>DiscountValue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/FinalPrice__c.field-meta.xml
<CustomField>
    <fullName>FinalPrice__c</fullName>
    <description>Preço final.</description>
    <label>FinalPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/FreightValue__c.field-meta.xml
<CustomField>
    <fullName>FreightValue__c</fullName>
    <description>Valor do frete.</description>
    <label>FreightValue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/MarginPercentage__c.field-meta.xml
<CustomField>
    <fullName>MarginPercentage__c</fullName>
    <description>Percentual da margem.</description>
    <label>MarginPercentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/PriceWithoutMargin__c.field-meta.xml
<CustomField>
    <fullName>PriceWithoutMargin__c</fullName>
    <description>Preço sem margem.</description>
    <label>PriceWithoutMargin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing /force-app/main/default/objects/OrderItem/fields/ProductionCost__c.field-meta.xml
<CustomField>
    <fullName>ProductionCost__c</fullName>
    <description>Custo de produção.</description>
    <label>ProductionCost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DesafioPricing/force-app/main/default/objects/OrderItem/fields/TaxPercentage__c.field-meta.xml
<CustomField>
    <fullName>TaxPercentage__c</fullName>
    <description>Percentual do imposto.</description>
    <label>TaxPercentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

DesafioPricing/force-app/main/default/classes/Services/PricingService/PricingService/PricingService.cls
public class PricingService {
    
    public static void calculateFinalPrice(OrderItem orderItem, Decimal freightValueEntered, Margem__c margem, Decimal taxPercentEntered, Decimal unitCost) {
        Decimal margemPercent = (margem != null && margem.MarginValuePercent__c != null) ? margem.MarginValuePercent__c : 0;
        Decimal taxPercent = (taxPercentEntered != null) ? taxPercentEntered : 0;
        Decimal productionCost = (unitCost != null) ? unitCost : 0;
        Decimal freightValue = (freightValueEntered != null) ? freightValueEntered : 0;
        
        //preco base
        Decimal basePrice = productionCost + freightValue;
        
        //preco sem margem
        Decimal priceWithoutMargin = basePrice * (1 + (taxPercent / 100));
        
        //preco final
        Decimal calculatedPrice = priceWithoutMargin * (1 + (margemPercent / 100));
        
        // preenchimento
        orderItem.ProductionCost__c = productionCost;   
        orderItem.MarginPercentage__c = margemPercent;
        orderItem.FreightValue__c = freightValue;
        orderItem.TaxPercentage__c = taxPercent;
        orderItem.PriceWithoutMargin__c = priceWithoutMargin; // preco sem margem
        orderItem.FinalPrice__c = calculatedPrice; // preco final, orderItem pedido 

        //garante q o unitPrice não seja null
        Decimal unitPriceEntered = (orderItem.UnitPrice != null) ? orderItem.UnitPrice : 0;
        
        // D. Cálculo do Desconto (Percent)
        if (calculatedPrice > 0) {
            orderItem.DiscountPercentage__c = (calculatedPrice - unitPriceEntered) / calculatedPrice;
            orderItem.DiscountValue__c = calculatedPrice - unitPriceEntered;
        }
        
        orderItem.UnitPrice = orderItem.FinalPrice__c;
    }
}