DesafioPokemon/force-app/main/default/objects/ChallengeUser__c/ChallengeUser__c.object-meta.xml
<CustomObject>
    <label>ChallengeUser</label>
    <nameField>
        <label>ChallengeUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChallengeUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DesafioPokemon/force-app/main/default/objects/ChallengeUser__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DesafioPokemon/force-app/main/default/classes/Batch/PokemonBatch.cls
public class PokemonBatch implements Database.Batchable<Integer> , Database.AllowsCallouts {
    
    public List<Integer> start(Database.BatchableContext bc) {
        List<Integer> repeat = new List<Integer>();
        for(Integer i = 0; i < 68; i++){
            repeat.add(i);
        }
        return repeat;
    }
    
    public void execute(Database.BatchableContext bc, List<Integer> scope) {
        List<ChallengeUser__c> usersToInsert = new List<ChallengeUser__c>();
        
        for(Integer page : scope) {
            Integer offset = page * 20;
            PokemonDTO pokemonDTO = PokemonService.integrationPokemon(offset);
            
            for(PokemonDTO.PokemonResultDTO iResults: pokemonDTO.results) {
                ChallengeUser__c user = new ChallengeUser__c();
                user.Name = iResults.name;
                user.url__c = iResults.url;
                usersToInsert.add(user);
            }
        }
        insert usersToInsert; 
    }
    
    public void finish(Database.BatchableContext bc) {
        // Post-processing logic here
    }
}